rpcdaemon: Glaze get block by number
erigontech/silkworm pull request #1590
Opened 2023-10-16 20:59 UTC by lupin012

2023-10-22 15:13 UTC, canepat requested changes

2023-10-22 15:13 UTC, canepat commented on silkworm/silkrpc/json/block.cpp
> +void make_glaze_json_withdrawls_content(GlazeJsonBlock& block_json_data, const BlockBody& block) {
`void make_glaze_json_withdrawals(const BlockBody& block, GlazeJsonBlock& json_block)`

2023-10-22 15:13 UTC, canepat commented on silkworm/silkrpc/json/block.cpp
> +void make_glaze_json_transaction_content(GlazeJsonTransaction& item, const silkworm::Transaction& transaction) {
`void make_glaze_json_transaction(const silkworm::Transaction& tx, GlazeJsonTransaction& json_tx)`

2023-10-22 15:13 UTC, canepat commented on silkworm/silkrpc/json/block.hpp
> +void make_glaze_json_content(std::string& reply, uint32_t id, const Block& b);
`void make_glaze_json_content(uint32_t id, const Block& b, std::string& json_reply);`

2023-10-22 15:13 UTC, canepat commented on silkworm/silkrpc/json/block.hpp
> +void make_glaze_json_null_content(std::string& reply, uint32_t id);
void make_glaze_json_null_content(uint32_t id, std::string& json_reply);

2023-10-22 21:20 UTC, lupin012 commented on silkworm/silkrpc/commands/eth_api.cpp
> +            make_glaze_json_null_content(reply, request["id"]);
ok

2023-10-22 21:20 UTC, lupin012 commented on silkworm/silkrpc/json/block.cpp
> +struct GlazeJsonNullBlock {
ok

2023-10-22 21:20 UTC, lupin012 commented on silkworm/silkrpc/json/block.cpp
> +void make_glaze_json_withdrawls_content(GlazeJsonBlock& block_json_data, const BlockBody& block) {
ok

2023-10-22 21:20 UTC, lupin012 commented on silkworm/silkrpc/json/block.cpp
> +void make_glaze_json_transaction_content(GlazeJsonTransaction& item, const silkworm::Transaction& transaction) {
ok

2023-10-22 21:20 UTC, lupin012 commented on silkworm/silkrpc/json/block.hpp
> +void make_glaze_json_content(std::string& reply, uint32_t id, const Block& b);
ok

2023-10-22 21:20 UTC, lupin012 commented on silkworm/silkrpc/json/block.hpp
> +void make_glaze_json_null_content(std::string& reply, uint32_t id);
ok

2023-10-23 06:08 UTC, canepat approved these changes

2023-10-23 06:08 UTC, merged