tests: a script to list dependencies of a module
erigontech/silkworm pull request #1867
Opened 2024-02-29 15:42 UTC by battlmonstr

Example:

```
% ./tests/deps/deps.py silkworm/node/snapshots
silkworm/node/snapshots module depends on:
 1. core/chain
 2. core/common
 3. core/types
 4. infra/common
 5. infra/concurrency
 6. infra/test_util
 7. node/db
 8. node/db/etl
 9. node/db/test_util
10. node/snapshots
11. node/snapshots/bittorrent
12. node/snapshots/config
13. node/snapshots/rec_split
14. node/snapshots/rec_split/common
15. node/snapshots/rec_split/encoding
16. node/snapshots/seg
17. node/snapshots/seg/common
18. node/snapshots/test_util
```

2024-02-29 19:48 UTC, canepat requested changes
I like the idea and usefulness, please move it directly to the project folder for better usability (moreover, it seems not related to tests)

2024-02-29 19:55 UTC, chfast commented
If these modules are CMake libs, CMake can generate a graph. https://cmake.org/cmake/help/latest/module/CMakeGraphVizOptions.html

2024-03-01 07:45 UTC, battlmonstr commented
@canepat maybe we have a special directory for such things? Like `tools` or `scripts`? There are some scripts in `cmake` folder which could also be moved there.

@chfast nice. I have a dream to use this tool and print out a wallpaper :) We are moving to a more modular approach, but we still have some monoliths. This script helps to understand what needs to be refactored to extract modules from monoliths. For example `node/snapshots` needs to be untied from `node/db` to become a separate library.

2024-03-01 09:11 UTC, JacekGlen commented
> > @canepat maybe we have a special directory for such things? Like `tools` or `scripts`? There are some scripts in `cmake` folder which could also be moved there.
> 
> @battlmonstr we don't but we should have a dedicated directory for such things: you can create a `scripts` directory and move there `deps.py` and other scripts.

Actually, can we make it a `tools` directory? I would also like to move `tests/docker/` there, as that is not strictly testing related.

2024-03-01 16:20 UTC, canepat approved these changes

2024-03-01 16:20 UTC, merged