capi: fork validator
erigontech/silkworm pull request #2201
Opened 2024-08-02 13:06 UTC by JacekGlen

Expose Fork Validator endpoints to CAPI:
- verify chain
- fork choice update

MDBX-go updated to match Erigon 3

2024-08-06 13:54 UTC, canepat requested changes
First of all, you should integrate and test block execution at the chain tip within Erigon2, so you don't want to update `mdbx-go` version now.

2024-08-07 15:13 UTC, canepat requested changes

2024-08-07 20:20 UTC, JacekGlen commented on silkworm/capi/silkworm.h
> +};
Done

2024-08-07 20:24 UTC, JacekGlen commented on silkworm/capi/silkworm_test.cpp
> +        auto result = new SilkwormForkValidatorValidationResult();
Done

2024-08-07 20:24 UTC, JacekGlen commented on silkworm/capi/silkworm_test.cpp
> +        delete result;
Done

2024-08-07 20:38 UTC, JacekGlen commented on silkworm/capi/silkworm.h
> +} bytes_32;
Done

2024-08-07 22:37 UTC, canepat approved these changes

2024-08-07 22:37 UTC, merged