rpcdaemon: fix stateDiff with CREATE and SELFDESTRUCT
erigontech/silkworm pull request #2278
Opened 2024-08-29 11:45 UTC by lupin012

2024-08-29 18:55 UTC, canepat requested changes

2024-08-29 18:55 UTC, canepat commented on silkworm/rpc/core/evm_trace.cpp
> +    return initial_ibs_.exists(address);
```suggestion
    if (balances_.contains(address) || nonces_.contains(address) || codes_.contains(address)) {
        return true;
    }

    return initial_ibs_.exists(address);
```

2024-08-29 18:55 UTC, canepat commented on silkworm/rpc/core/evm_trace.cpp
> +    }
```suggestion
    balances_.erase(address);
    nonces_.erase(address);
    codes_.erase(address);
```

2024-08-29 20:58 UTC, chfast reviewed
Do you have any kind of regression tests for such changes?

2024-08-30 09:29 UTC, canepat approved these changes

2024-08-30 09:37 UTC, lupin012 commented
> Do you have any kind of regression tests for such changes?

Yes I have some new rpc-integration-tests cover this scenarios and I have many other rpc-integration-tests ("to try") to  avoid regression. 
These changes are related only tracer implementation (to be more aligned to erigon/rpcdaemon), the change on intra-block-state are just a getter.

2024-08-30 09:38 UTC, merged