rpcdaemon: page_token management in range ops
erigontech/silkworm pull request #2477
Opened 2024-11-04 23:04 UTC by Sixtysixter

Fix for page_token management in 
- RemoteTransaction::history_range
- RemoteTransaction::index_range
- RemoteTransaction::domain_range

2024-11-05 13:28 UTC, canepat requested changes

2024-11-05 13:28 UTC, canepat commented on silkworm/db/kv/api/endpoint/paginated_sequence.hpp
> +    using Paginator = std::function<Task<PageResult>(const std::string& page_token)>;
```suggestion
    using Paginator = std::function<Task<PageResult>(std::string)>;
```

2024-11-05 13:28 UTC, canepat commented on silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
> +            PaginatedUint64 paginated1{lambda1}, paginated2{lambda2};
This change seems unnecessary

2024-11-05 13:28 UTC, canepat commented on silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
> +            PaginatedUint64 paginated1{lambda1}, paginated2{lambda2};
This change seems unnecessary

2024-11-05 13:28 UTC, canepat commented on silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
> +            PaginatedUint64 paginated{lambda};
This change seems unnecessary

2024-11-05 13:28 UTC, canepat commented on silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
> +    PaginatedUint64 paginated{lambda};
This change seems unnecessary

2024-11-05 14:17 UTC, Sixtysixter commented on silkworm/db/kv/api/endpoint/paginated_sequence.hpp
> +    using Paginator = std::function<Task<PageResult>(const std::string& page_token)>;
done

2024-11-05 14:17 UTC, Sixtysixter commented on silkworm/db/kv/api/endpoint/paginated_sequence.hpp
> +    using Paginator = std::function<Task<PageResult>(const std::string& page_token)>;
Done

2024-11-05 14:20 UTC, Sixtysixter commented on silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
> +            PaginatedUint64 paginated1{lambda1}, paginated2{lambda2};
as previous comment

2024-11-05 14:20 UTC, Sixtysixter commented on silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
> +    PaginatedUint64 paginated{lambda};
as previous comment

2024-11-05 15:50 UTC, Sixtysixter commented on silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
> +            PaginatedUint64 paginated{lambda};
done

2024-11-07 07:40 UTC, canepat approved these changes

2024-11-07 07:41 UTC, merged